
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restoct-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restoct
  template:
    metadata:
      labels:
        app: restoct
    spec:
      containers:
        - name: restoct-app
          image: restoct-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/restoct"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"  # Se usa "root" como el usuario para MySQL
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_ROOT_PASSWORD  # Usamos MYSQL_ROOT_PASSWORD en lugar de MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: restoct-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: restoct
  type: LoadBalancer
